### ISSUE TITLE
Change the screenshot name

### ISSUE THREAD

**Issue by bogdannitica** [mlison/protractor-jasmine2-screenshot-reporter#26]
Are there any options in order to change the screenshots name?

**Comment by mlison** [comment]
By default, filenames will be random so that they don't conflict with one another.

You can however specify your own pathBuilder function in the options. This function is called for every single spec, and whatever it returns will be used as filename. Example [here](https://github.com/mlison/protractor-jasmine2-screenshot-reporter#path-builder-optional).

**Comment by bogdannitica** [comment]
Thanks mlison, I've managed to change the screenshot name.
Marked this issue as closed
